[toolchain]
package_manager = "npm"
anchor_version = "0.29.0"
[build]
arch = "sbf"
[features]
resolution = true
skip-lint = false
[programs.localnet]
nft_auth_program = "GdcoT7hsvLJsKWebA5em5127kQvEmh9JKma2YT9CWsYz"
[programs.devnet]
nft_auth_program = "GdcoT7hsvLJsKWebA5em5127kQvEmh9JKma2YT9CWsYz"
[registry]
url = "https://api.apr.dev"
[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
[scripts]
test = "npm run ts-mocha"